apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  labels:
    app.kubernetes.io/component: webhook
    pipeline.tekton.dev/release: v0.37.2
  {{- include "tekton-pipelines.labels" . | nindent 4 }}