apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-webhook
  labels:
    app: tekton-pipelines-webhook
    app.kubernetes.io/component: webhook
    pipeline.tekton.dev/release: v0.37.2
    version: v0.37.2
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.type }}
  selector:
    app.kubernetes.io/component: webhook
  {{- include "tekton-pipelines.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.webhook.ports | toYaml | nindent 2 -}}